---
title: "CellRanger Data - Part 4 (Seurat tutorial)"
author: "Craig Duncan"
date: "11-14 March 2021; 6 April 2021"
output:
  html_document:
    df_print: paged
---

# Comments on Seurat Tutorial from Satija Lab

We need at least R version 4 installed to run Seurat.

Having done that, we start to progress with using the above files in the above directory with the pbmc 10X functions.

## Basic setup in R

```{R}
# install.packages('Seurat')
library(dplyr)
library(Seurat) 
library(Matrix)

# Load the PBMC dataset [note Seurat comes with a pbmc_small example but since it has already had some preprocessing steps applied to it, this file provides an illustration with less in-built assumptions]
# download the pbmc data as recommended at the [SeuratTutePage](https://satijalab.org/seurat/archive/v3.0/pbmc3k_tutorial.html).  Seurat comes pre-installed with only a small version of this data (pbmc_small). 
# When you have downloaded the data and put it into the data folder and subfolders as described below, run this script:
pbmc.data <- Read10X(data.dir = "data/pbmc3k/filtered_gene_bc_matrices/hg19/")
# Create Seurat object
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
```

# Having a look at pbmc.data (a dgC matrix) - using R and Seurat

pmbc.data object is a large dgCmatrix, dimensions 32738 (genes) x 2700 (barcodes) = 88,392,600 elements.

Here, i and x both have the total number of entries (2286884) but different information.

Type this in to see what the data looks like:

```{R}
# Lets examine a few genes in the first thirty cells
pbmc.data[c("CD3D", "TCL1A", "MS4A1"), 1:30]
```

The Seurat tutorial notes:
```
The . values in the matrix represent 0s (no molecules detected). Since most values in an scRNA-seq matrix are 0, Seurat uses a sparse-matrix representation whenever possible. This results in significant memory and speed savings for Drop-seq/inDrop/10x data.
```
## dgC matrix to SeuratObject

The next line (CreateSeuratObject()) transforms the data in the matrix file into a Seurat Object, which includes several other internal data objects and summary data tables.

The main Seurat object is this (summary):

```
> pbmc
An object of class Seurat 
13714 features across 2700 samples within 1 assay 
Active assay: RNA (13714 features, 0 variable features)
```

To access the summary count data for each gene (across all cells) that you have imported then you need to access an internal 'counts' vector stored inside the Seurat object.  
```{R}
pbmc$nCount_RNA # This is the vector in the data.frame that is in the Seurat object meta.data slot. 
```

## Accessing the imported raw count data in Seurat (if needed)

nb:  "the count matrix is stored in pbmc[["RNA"]]@counts."
see https://satijalab.org/seurat/articles/essential_commands.html

# QC tests

What is a low quality cell?
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4758103/

